# Generated by Django 5.1.1 on 2024-09-25 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('cost', models.PositiveIntegerField()),
                ('storage', models.PositiveIntegerField()),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MemorialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('about', models.TextField()),
                ('current_storage', models.PositiveIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='associated_memorial', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('current_plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='associated_plan', to='user.plan')),
            ],
        ),
    ]
