# Generated by Django 5.1.1 on 2024-09-25 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profilepermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorialprofile',
            name='users',
        ),
    ]
